### ISSUE TITLE
Not Working on Python 3.12

### ISSUE THREAD

**Issue by OneNc** [Fadi002/regboss#3]
i got error
AttributeError: module 'zlib' has no attribute 'lzma'

**Comment by Fadi002** [comment]
The error makes zero sense send a screenshot if you can

**Comment by OneNc** [comment]
sorry its my bad, actually its cannot encode byte 0x90 byte (═) this symbol

**Comment by Fadi002** [comment]
> sorry its my bad, actually its cannot encode byte 0x90 byte (═) this symbol

Can you tell me which line exactly has the error ?

**Comment by OneNc** [comment]
> 
![image](https://github.com/Fadi002/regboss/assets/13020002/dfeea771-e409-41f7-a363-291a87844cfe)

**Comment by Fadi002** [comment]
> > 
> 
> ![image](https://private-user-images.githubusercontent.com/13020002/334405668-dfeea771-e409-41f7-a363-291a87844cfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDA1NTIsIm5iZiI6MTcxNjk0MDI1MiwicGF0aCI6Ii8xMzAyMDAwMi8zMzQ0MDU2NjgtZGZlZWE3NzEtZTQwOS00MWY3LWEzNjMtMjkxYTg3ODQ0Y2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDIzNTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMTE3M2MwMDQ4YjM2ZGYxNTYzM2JjOTY3ZmZjYTI0MTI1ZjRkZDNmYTRiZTk0Njg0YmNkODI0YzBmZjc0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5CshYHl-YVsHfUwMSmZSLUBAutC9k3IDCN5-3cOBIZY)

try to replace line 97 in regboss.py https://github.com/Fadi002/regboss/blob/116fe7434c2e384cdfa79c7735ef7301b31ecbdc/regboss.py#L97
```py
code = open(file, 'r').read()
```
with 
```py
code = open(file, 'r',encoding="utf8").read()
```

**Comment by OneNc** [comment]
its worked, i think my code is wrong. so i never change on regboss.py
